### PR TITLE
Fixed the navigation bar issue

### PR DESCRIPTION
**Pull request by rhnprabhune**

### CODE REVIEW

**Comment by krishnasaurabh** [comment]
The nav bar issue is fixed, but there are some other issues with session and login, logout, I will create another issue for that.

**Review by krishnasaurabh — APPROVED** [review]

**Comment by rhnprabhune** [comment]
Is #4 for what you are saying ?

**Comment by krishnasaurabh** [comment]
No, its a major flaw, the logout doesn't actually do anything. we need to implement it.

**Comment by rhnprabhune** [comment]
Right. You can create a separate issue for it. For now Is this good to be merged ?

**Comment by krishnasaurabh** [comment]
yes please nerge it

**Pull request merged**
